// Package api_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api_gen

// CandidatesResultData defines model for CandidatesResultData.
type CandidatesResultData struct {
	CandidateDescription string  `json:"candidateDescription"`
	CandidateID          string  `json:"candidateID"`
	CandidateName        string  `json:"candidateName"`
	VoteScore            float32 `json:"voteScore"`
}

// ErrorResultData defines model for ErrorResultData.
type ErrorResultData struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// CandidatesResult defines model for CandidatesResult.
type CandidatesResult struct {
	Data *[]CandidatesResultData `json:"data,omitempty"`
}

// ErrorResult defines model for ErrorResult.
type ErrorResult struct {
	Error *ErrorResultData `json:"error,omitempty"`
}

// CreateNewCandidate defines model for CreateNewCandidate.
type CreateNewCandidate struct {
	CandidateDescription string `json:"candidateDescription"`
	CandidateName        string `json:"candidateName"`
}

// UpdateCandidate defines model for UpdateCandidate.
type UpdateCandidate struct {
	CandidateDescription *string `json:"candidateDescription,omitempty"`
	CandidateID          string  `json:"candidateID"`
	CandidateName        *string `json:"candidateName,omitempty"`
}

// CreateNewCandidateJSONRequestBody defines body for CreateNewCandidate for application/json ContentType.
type CreateNewCandidateJSONRequestBody CreateNewCandidate

// UpdateCandidateInfoJSONRequestBody defines body for UpdateCandidateInfo for application/json ContentType.
type UpdateCandidateInfoJSONRequestBody UpdateCandidate
