// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go

// Package mock_vote_history_repo is a generated GoMock package.
package mock_vote_history_repo

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	vote_history "github.com/pathai95441/muang_thai_vote_service/src/repositories/vote_history"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// CountVote mocks base method.
func (m *MockIRepository) CountVote(ctx context.Context, candidateID string) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVote", ctx, candidateID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountVote indicates an expected call of CountVote.
func (mr *MockIRepositoryMockRecorder) CountVote(ctx, candidateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVote", reflect.TypeOf((*MockIRepository)(nil).CountVote), ctx, candidateID)
}

// DeletedVoted mocks base method.
func (m *MockIRepository) DeletedVoted(ctx context.Context, tx *sql.Tx, historyID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletedVoted", ctx, tx, historyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletedVoted indicates an expected call of DeletedVoted.
func (mr *MockIRepositoryMockRecorder) DeletedVoted(ctx, tx, historyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletedVoted", reflect.TypeOf((*MockIRepository)(nil).DeletedVoted), ctx, tx, historyID)
}

// GetByUserID mocks base method.
func (m *MockIRepository) GetByUserID(ctx context.Context, userID string) (*vote_history.VoteHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*vote_history.VoteHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockIRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockIRepository)(nil).GetByUserID), ctx, userID)
}

// GetUserVote mocks base method.
func (m *MockIRepository) GetUserVote(ctx context.Context, userID, candidateID string) (*vote_history.VoteHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserVote", ctx, userID, candidateID)
	ret0, _ := ret[0].(*vote_history.VoteHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserVote indicates an expected call of GetUserVote.
func (mr *MockIRepositoryMockRecorder) GetUserVote(ctx, userID, candidateID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserVote", reflect.TypeOf((*MockIRepository)(nil).GetUserVote), ctx, userID, candidateID)
}

// Insert mocks base method.
func (m *MockIRepository) Insert(ctx context.Context, tx *sql.Tx, history vote_history.VoteHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockIRepositoryMockRecorder) Insert(ctx, tx, history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIRepository)(nil).Insert), ctx, tx, history)
}
