openapi: '3.0.2'
info:
  title: vote
  version: '1.0'
servers:
  - url: http://{hostname}
    variables:
      hostname:
        default: localhost:8080
paths:
  /candidates:
    post:
      summary: Get All Candidate
      operationId: GetAllCandidate
      tags:
        - candidate
      parameters:
        - name: sortBy
          in: query
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/CandidatesResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
  /candidate:
    post:
      summary: Create new candidate
      operationId: CreateNewCandidate
      tags:
        - candidate
      requestBody:
        $ref: "#/components/requestBodies/CreateNewCandidate"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
    put:
      summary: Update Candidate Info
      operationId: Update Candidate info
      tags:
        - candidate
      requestBody:
        $ref: "#/components/requestBodies/UpdateCandidate"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
  /candidate/{candidateID}:
    delete:
      summary: Delete candidate
      operationId: DeleteCandidateByID
      tags:
        - candidate
      parameters:
        - name: candidateID
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
  /user:
    post:
      summary: Create new User
      operationId: CreateNewUser
      tags:
        - user
      requestBody:
        $ref: "#/components/requestBodies/CreateNewUser"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
  /sign_in:
    post:
      summary: SignIn
      operationId: SignIn
      tags:
        - auth
      requestBody:
        $ref: "#/components/requestBodies/SignIn"
      responses:
        "200":
          $ref: "#/components/responses/SignInResult"
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
  /vote_candidate:
    post:
      summary: VoteCandidate
      operationId: VoteCandidate
      tags:
        - vote
      requestBody:
        $ref: "#/components/requestBodies/VoteCandidate"
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/ErrorResult"
        "500":
          $ref: "#/components/responses/ErrorResult"
components:
  responses:
    ErrorResult:
      description: Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                $ref: "#/components/schemas/ErrorResultData"
    CandidatesResult:
      description: CandidatesResult
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items: 
                  $ref: "#/components/schemas/CandidatesResultData"
    SignInResult:
      description: SignInResult
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: "#/components/schemas/SignInResultData"
  requestBodies:
    CreateNewCandidate:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - candidateName
                - candidateDescription
              properties:
                candidateName:
                  type: string
                candidateDescription:
                  type: string
    UpdateCandidate:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - candidateID
              properties:
                candidateID:
                  type: string
                candidateName:
                  type: string
                candidateDescription:
                  type: string
    CreateNewUser:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - password
                - email
                - roleID
              properties:
                userName:
                  type: string
                password:
                  type: string
                email:
                  type: string
                roleID:
                  type: number
    SignIn:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userName
                - password
              properties:
                userName:
                  type: string
                password:
                  type: string
    VoteCandidate:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - candidateID
                - unVote
              properties:
                candidateID:
                  type: string
                unVote:
                  type: boolean
  schemas:
    CandidatesResultData:
      type: object
      required:
        - candidateID
        - candidateName
        - candidateDescription
        - voteScore
      properties:
        candidateID:
          type: string
        candidateName:
          type: string
        candidateDescription:
          type: string
        voteScore:
          type: number
    SignInResultData:
      type: object
      required:
        - token
        - userID
        - userName
        - roleID
        - voteCandidateID
      properties:
        token:
          type: string
        userID:
          type: string
        userName:
          type: string
        roleID:
          type: number
        voteCandidateID:
          type: string
    ErrorResultData:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
