// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db_models_gen

var TableNames = struct {
	Candidate        string
	Role             string
	SchemaMigrations string
	Users            string
	VoteConfig       string
	VoteHistory      string
}{
	Candidate:        "candidate",
	Role:             "role",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
	VoteConfig:       "vote_config",
	VoteHistory:      "vote_history",
}
