// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db_models_gen

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCandidates(t *testing.T) {
	t.Parallel()

	query := Candidates()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCandidatesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCandidatesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Candidates().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCandidatesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CandidateSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCandidatesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CandidateExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Candidate exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CandidateExists to return true, but got false.")
	}
}

func testCandidatesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	candidateFound, err := FindCandidate(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if candidateFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCandidatesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Candidates().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCandidatesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Candidates().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCandidatesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	candidateOne := &Candidate{}
	candidateTwo := &Candidate{}
	if err = randomize.Struct(seed, candidateOne, candidateDBTypes, false, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}
	if err = randomize.Struct(seed, candidateTwo, candidateDBTypes, false, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = candidateOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = candidateTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Candidates().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCandidatesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	candidateOne := &Candidate{}
	candidateTwo := &Candidate{}
	if err = randomize.Struct(seed, candidateOne, candidateDBTypes, false, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}
	if err = randomize.Struct(seed, candidateTwo, candidateDBTypes, false, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = candidateOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = candidateTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func candidateBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func candidateAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Candidate) error {
	*o = Candidate{}
	return nil
}

func testCandidatesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Candidate{}
	o := &Candidate{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, candidateDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Candidate object: %s", err)
	}

	AddCandidateHook(boil.BeforeInsertHook, candidateBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	candidateBeforeInsertHooks = []CandidateHook{}

	AddCandidateHook(boil.AfterInsertHook, candidateAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	candidateAfterInsertHooks = []CandidateHook{}

	AddCandidateHook(boil.AfterSelectHook, candidateAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	candidateAfterSelectHooks = []CandidateHook{}

	AddCandidateHook(boil.BeforeUpdateHook, candidateBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	candidateBeforeUpdateHooks = []CandidateHook{}

	AddCandidateHook(boil.AfterUpdateHook, candidateAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	candidateAfterUpdateHooks = []CandidateHook{}

	AddCandidateHook(boil.BeforeDeleteHook, candidateBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	candidateBeforeDeleteHooks = []CandidateHook{}

	AddCandidateHook(boil.AfterDeleteHook, candidateAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	candidateAfterDeleteHooks = []CandidateHook{}

	AddCandidateHook(boil.BeforeUpsertHook, candidateBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	candidateBeforeUpsertHooks = []CandidateHook{}

	AddCandidateHook(boil.AfterUpsertHook, candidateAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	candidateAfterUpsertHooks = []CandidateHook{}
}

func testCandidatesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCandidatesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(candidateColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCandidateToManyVoteHistories(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Candidate
	var b, c VoteHistory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, voteHistoryDBTypes, false, voteHistoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, voteHistoryDBTypes, false, voteHistoryColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CandidateID = a.ID
	c.CandidateID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.VoteHistories().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CandidateID == b.CandidateID {
			bFound = true
		}
		if v.CandidateID == c.CandidateID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CandidateSlice{&a}
	if err = a.L.LoadVoteHistories(ctx, tx, false, (*[]*Candidate)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.VoteHistories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.VoteHistories = nil
	if err = a.L.LoadVoteHistories(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.VoteHistories); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testCandidateToManyAddOpVoteHistories(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Candidate
	var b, c, d, e VoteHistory

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, candidateDBTypes, false, strmangle.SetComplement(candidatePrimaryKeyColumns, candidateColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*VoteHistory{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, voteHistoryDBTypes, false, strmangle.SetComplement(voteHistoryPrimaryKeyColumns, voteHistoryColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*VoteHistory{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddVoteHistories(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.CandidateID {
			t.Error("foreign key was wrong value", a.ID, first.CandidateID)
		}
		if a.ID != second.CandidateID {
			t.Error("foreign key was wrong value", a.ID, second.CandidateID)
		}

		if first.R.Candidate != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Candidate != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.VoteHistories[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.VoteHistories[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.VoteHistories().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCandidatesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCandidatesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CandidateSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCandidatesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Candidates().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	candidateDBTypes = map[string]string{`ID`: `varchar`, `CandidateName`: `varchar`, `CandidateDescription`: `varchar`, `VoteScore`: `int`, `CreatedAt`: `timestamp`, `CreatedBy`: `varchar`, `UpdatedAt`: `timestamp`, `UpdatedBy`: `varchar`, `DeletedAt`: `timestamp`, `DeletedBy`: `varchar`}
	_                = bytes.MinRead
)

func testCandidatesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(candidatePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(candidateAllColumns) == len(candidatePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidatePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCandidatesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(candidateAllColumns) == len(candidatePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Candidate{}
	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidateColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, candidateDBTypes, true, candidatePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(candidateAllColumns, candidatePrimaryKeyColumns) {
		fields = candidateAllColumns
	} else {
		fields = strmangle.SetComplement(
			candidateAllColumns,
			candidatePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CandidateSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCandidatesUpsert(t *testing.T) {
	t.Parallel()

	if len(candidateAllColumns) == len(candidatePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLCandidateUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Candidate{}
	if err = randomize.Struct(seed, &o, candidateDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Candidate: %s", err)
	}

	count, err := Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, candidateDBTypes, false, candidatePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Candidate struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Candidate: %s", err)
	}

	count, err = Candidates().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
