// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db_models_gen

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Candidates", testCandidatesUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("VoteConfigs", testVoteConfigsUpsert)

	t.Run("VoteHistories", testVoteHistoriesUpsert)
}
